name: "Russell Spitzer's Blog"
description: "Some guy's blog"


url: "www.russellspitzer.com"

markdown: kramdown
kramdown:
  input: "GFM"
  syntax_highlighter: rouge

highlighter: rouge
permalink: pretty

paginate: 10

gems: [jekyll-paginate, kramdown, rouge]